Imported Upstream version 4.13.92.dfsg.1

diff --git a/install-info/tests/defs.in b/install-info/tests/defs.in
--- a/install-info/tests/defs.in
+++ b/install-info/tests/defs.in
@@ -1,5 +1,5 @@
 # @configure_input@
-# $Id: defs.in,v 1.3 2012/11/26 18:30:49 karl Exp $
+# $Id: defs.in,v 1.6 2012/12/02 23:12:22 karl Exp $
 # 
 # Copyright 2008, 2012 Free Software Foundation, Inc.
 #
@@ -26,7 +26,7 @@ CDPATH=; unset CDPATH
 
 # Ensure we are running from the right directory.
 if test ! -f ./defs; then
-   echo "defs: not found in current directory" 1>&2
+   echo "$0: defs: not found in current directory." 1>&2
    exit 1
 fi
 
@@ -36,6 +36,33 @@ if test -z "$srcdir"; then
    # compute $srcdir.
    srcdir=`echo "$0" | sed -e 's,/[^\\/]*$,,'`
    test $srcdir = $0 && srcdir=.
+fi
+
+# Two variables we use in the test scripts:
+top_builddir=@top_builddir@
+install_info=${top_builddir}/install-info/ginstall-info
+export install_info
+#
+top_srcdir=@top_srcdir@
+testdir=${top_srcdir}/install-info/tests
+export testdir
+
+if test -z "$TMPDIR"; then
+  TMPDIR=/tmp
+  export TMPDIR
+fi
+
+# In case someone pedantic insists on using grep -E.
+: ${EGREP=egrep}
+
+# Systems which define $COMSPEC or $ComSpec use semicolons to separate
+# directories in TEXINPUTS -- except for Cygwin et al., where COMSPEC
+# might be inherited, but : is used.
+if test -n "$COMSPEC$ComSpec" \
+   && uname | $EGREP -iv 'cygwin|mingw|djgpp' >/dev/null; then
+  path_sep=";"
+else
+  path_sep=":"
 fi
 
 # Return true if PROG is somewhere in PATH, else false.
@@ -62,13 +89,18 @@ findprog ()
   return 1
 }
 
-
-# Two variables we use in the test scripts.
-
-top_builddir=@top_builddir@
-install_info=${top_builddir}/install-info/ginstall-info
-export install_info
-
-top_srcdir=@top_srcdir@
-testdir=${top_srcdir}/install-info/tests
-export testdir
+if findprog mktemp; then :; else
+# Some deficient proprietary systems lack mktemp; kowtow to them.
+# Our mktemp substitute doesn't need all the features of real mktemp;
+# our tests here only use it in the most simplistic way, to create a
+# temp file.  The autoconf manual suggests doing it in a temporary
+# directory (mode 700).  ($RANDOM may expand to nothing, but that's ok.)
+# We do not even bother to expand the X's in the template ...
+mktemp ()
+{
+  dir=$TMPDIR/iimktemp$$-$RANDOM
+  (umask 077 && mkdir "$dir")
+  touch "$dir/$1" || return 1
+  echo "$dir/$1"
+}
+fi
