change postinst and postrm for texinfo, fix control for new texlive name

diff --git a/debian/texinfo.postinst b/debian/texinfo.postinst
--- a/debian/texinfo.postinst
+++ b/debian/texinfo.postinst
@@ -1,10 +1,68 @@
 #!/bin/sh -e
 
-#
-# do the following commands as soon as they are present
-#
-if which update-fmtutil > /dev/null ; then update-fmtutil ; fi
-if which mktexlsr >/dev/null; then mktexlsr; fi
-if which fmtutil-sys > /dev/null ; then fmtutil-sys --missing ; fi
+build_format_if_format_exists ()
+{
+    X=`fmtutil-sys --listcfg | grep "^$2[[:space:]]" || true`
+    if [ ! "X$X" = "X" ] ; then
+        if [ "X$1" = "X--byhyphen" ] ; then
+	    build_format --byhyphen $3
+	else
+            build_format $1 $2
+	fi
+    fi
+}
+
+build_format ()
+{
+    tempfile=`mktemp -p /tmp fmtutil.XXXXXXXX`
+    echo -n "Building format(s) $1 `basename "$2"`. This may take some time. ..."
+    if fmtutil-sys $1 $2 > $tempfile 2>&1 ; then
+        rm -f $tempfile
+	echo " done."
+    else
+        echo
+	echo "fmtutil-sys failed. Output has been stored in"
+	echo "$tempfile"
+	echo "Please include this file if you report a bug."
+	echo
+	exit 1
+    fi
+}
+
+update_lsr_files ()
+{
+    tempfile=`mktemp -p /tmp mktexlsr.XXXXXXXX`
+    echo -n "Running mktexlsr. This may take some time. ..."
+    if mktexlsr /usr/share/texmf /var/lib/texmf > $tempfile 2>&1 ; then
+         rm -f $tempfile
+	 echo " done."
+    else
+          echo
+	  echo "mktexlsr failed. Output has been stored in"
+	  echo "$tempfile"
+	  echo "Please include this file if you report a bug."
+	  echo
+	  exit 1
+    fi
+}
+
+# common.functions end
+case "$1" in
+    configure|abort-upgrade|abort-remove|abort-deconfigure)
+	#
+	# do the following commands as soon as they are present
+	#
+	if which update-fmtutil > /dev/null ; then update-fmtutil ; fi
+	if which mktexlsr >/dev/null; then update_ls_files; fi
+	if which fmtutil-sys > /dev/null ; then 
+	    build_format_if_format_exists --byfmt texinfo
+	    build_format_if_format_exists --byfmt cyrtexinfo
+	fi
+	;;
+    *)
+    	echo "postinst called with unknown argument \`$1'" >&2
+	exit 1
+    ;;
+esac
 
 #DEBHELPER#
diff --git a/debian/texinfo.postrm b/debian/texinfo.postrm
--- a/debian/texinfo.postrm
+++ b/debian/texinfo.postrm
@@ -1,14 +1,62 @@
 #!/bin/sh -e
 
-#
-# do the following commands as soon as they are present
-#
-if which update-fmtutil > /dev/null ; then update-fmtutil ; fi
-if which mktexlsr >/dev/null; then mktexlsr; fi
+check_run_without_errors ()
+{
+    tempfile=`mktemp -p /tmp checkrun.XXXXXXXX`
+    if which $1  >/dev/null; then
+        echo -n "Running $*. This may take some time. ..."
+	set +e
+        $* > $tempfile 2>&1
+	if [ $? = 0 ] ; then
+	  rm -f $tempfile
+	  echo " done."
+	else
+	  echo
+	  echo "$* failed. Output has been stored in"
+	  echo "$tempfile"
+	  echo "If tex-common is not configured you can ignore this error message!"
+	  echo "Otherwise please include this file if you report a bug."
+	  echo
+	fi
+	set -e
+    else
+        rm -f $tempfile
+    fi
+    return 0
+}
 
-#
-# remove the cyrtexinfo format files in case they have been created
-#
-rm -f /var/lib/texmf/web2c/cyrtexinfo.fmt /var/lib/texmf/web2c/cyrtexinfo.log
+update_lsr_files ()
+{
+    tempfile=`mktemp -p /tmp mktexlsr.XXXXXXXX`
+    echo -n "Running mktexlsr. This may take some time. ..."
+    if mktexlsr /usr/share/texmf /usr/share/texmf-texlive /var/lib/texmf > $tempfile 2>&1 ; then
+         rm -f $tempfile
+	 echo " done."
+    else
+          echo
+	  echo "mktexlsr failed. Output has been stored in"
+	  echo "$tempfile"
+	  echo "Please include this file if you report a bug."
+	  echo
+	  exit 1
+    fi
+}
+
+case "$1" in
+    remove|disappear)
+        rm -f /var/lib/texmf/web2c/texinfo.*
+        rm -f /var/lib/texmf/web2c/cyrtexinfo.*
+        check_run_without_errors update-fmtutil
+	check_run_without_errors mktexlsr
+    ;;
+    purge|upgrade|failed-upgrade|abort-upgrade|abort-install)
+    ;;
+    *)
+    	echo "postrm called with unknown argument \`$1'" >&2
+	exit 1
+    ;;
+esac
 
 #DEBHELPER#
+
+exit 0
